# Generated by Django 4.1.7 on 2023-04-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_goal', models.IntegerField(default=0)),
                ('current_savings', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
            ],
        ),
    ]
