# Generated by Django 4.1.7 on 2023-04-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='income',
            new_name='monthly_income',
        ),
    ]
