# Generated by Django 4.1.7 on 2023-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_income_savings_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('R', 'Resturant'), ('B', 'Bills & utilities'), ('T', 'Transportation'), ('E', 'Entertainment'), ('D', 'Education'), ('V', 'Travel'), ('G', 'Groceries'), ('A', 'Gas'), ('H', 'Health & Wellness'), ('S', 'Shopping'), ('O', 'Other')], default='R', max_length=2, verbose_name='Choose a Catergory'),
        ),
    ]
