# Generated by Django 4.1.7 on 2023-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_expenses_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Bills & Utilities', 'Bills & Utilities'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Travel', 'Travel'), ('Groceries', 'Groceries'), ('Gas', 'Gas'), ('Health & Wellness', 'Health & Wellness'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Restaurant', max_length=25),
        ),
    ]
